version: '3.7'
services:
  mongodb:
    image: mongo:5.0.15
    container_name: fullstack-jwt-next-nest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  mongodb_data_container:

  # docker compose -p fullstack-jwt-next-nest up -d
